### ISSUE TITLE
Confirm choice

### ISSUE THREAD

**Issue by amandou** [amandou/Jame-Gam-Christmas-Edition#10]
**Expected Behavior**
When a card is selected, confirmed can be pressed. After interact, the selected card must disappear, a new card can be drawn from the deck and its button has to be not interactive. The last behavior just change when a new card is selected.

**Tasks**
- [x] Update available card slots.
- [x] Hide confirmed card.
- [x] Undo confirm button selection after button is clicked.
