### ISSUE TITLE
Select card

### ISSUE THREAD

**Issue by amandou** [amandou/Jame-Gam-Christmas-Edition#11]
**Expected Behavior**
When the mouse is on the card, it has to move some position in y axis. When the card is clicked, it is selected and confirm button can be pressed. Cards confirm button is not interactive if there are no cards selected.

**Tasks**
- [x] Move card some positions in y axis when mouse is on the card.
- [x] Selected card and make confirm button can be pressed. 
- [x] When there are no selected cards confirm button is not interactive.
