### ISSUE TITLE
Draw a card from deck

### ISSUE THREAD

**Issue by amandou** [amandou/Jame-Gam-Christmas-Edition#9]
**Expected Behavior**
Must have a button responsible to show a card on the table when it's clicked. When a card is removed from the deck, its counter must be updated. This behavior should only work when there are cards in the deck pile.

**Tasks**
- [x] Create deck image.
- [x] Show how many cards are in the deck. 
- [x] Create a button draw card button.
- [x] When click in the button, the card has to be shown in the table.
